spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 1800000
      leak-detection-threshold: 30000

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
server:
  tomcat:
    threads:
      max: 400
      min-spare: 20
    max-connections: 8192
    accept-count: 200
    connection-timeout: 5000